# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".csv",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".txt",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "example.py",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 132
indent-width = 4

# Use Python 3.11
target-version = "py311"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["ALL"]
# select = ["E4", "E7", "E9", "F", "I", "ANN"]
ignore = [
    "ANN206", # missing-return-type-class-method
    "ASYNC220", # create-subprocess-in-async-function
    "ASYNC221", # run-process-in-async-function
    "C901", # complex-structure
    "COM812", # missing-trailing-comma
    "D100", # undocumented-public-module
    "D203", # one-blank-line-before-class
    "D211", # blank-line-before-class
    "D213", # multi-line-summary-second-line
    "FBT001", # boolean-type-hint-positional-argument
    "FBT002", # boolean-default-value-positional-argument
    "G004", # logging-f-string
    "PLW0603", # global-statement
    "PLW2901", # redefined-loop-name
    "PLR0912", # too-many-branches
    "PLR0915", # too-many-statements
    "I001", # unsorted-imports (based on isort, but we sort with ruff logic)
    "ISC001", # single-line-implicit-string-concatenation
    "S602", # subprocess-popen-with-shell-equals-true
    "S603", # subprocess-without-shell-equals-true
    "S605", # start-process-with-a-shell
    "S607", # start-process-with-partial-path
    "SIM117", # multiple-with-statements
    "SLF001", # private-member-access
    "T201", # print
    "T203", # pprint
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"
